[package]
name = "adaptive_boss"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
astraweave-core = { path = "../../astraweave-core" }
astraweave-director = { path = "../../astraweave-director" }
