[package]
name = "debug_overlay"
version = "0.1.0"
license.workspace = true
edition = "2021"

[dependencies]
anyhow = { workspace = true }
eframe = { workspace = true }
egui = { workspace = true }
astraweave-core = { path = "../../astraweave-core" }
