[workspace]
members = [
  "astraweave-core",
  "astraweave-ai",
  "astraweave-sdk",
  "astraweave-director",
  "astraweave-memory",
  "astraweave-ipc",
  "astraweave-llm",        # NEW
  "astraweave-persona",    # NEW
  "astraweave-author",     # NEW
  "astraweave-net",        # NEW
  "examples/hello_companion",
  "examples/adaptive_boss",
  "examples/companion_profile",
  "examples/ipc_loopback",
  "examples/debug_overlay",
  "examples/llm_toolcall",    # NEW
  "examples/phase_director",  # NEW
  "examples/persona_loader",  # NEW
  "examples/rhai_authoring",  # NEW
  "examples/coop_server",     # NEW
  "examples/coop_client",     # NEW
]
resolver = "2"

[workspace.package]
version = "0.3.0"
edition = "2021"

[workspace.dependencies]
anyhow = "1"
thiserror = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"
zip = "0.6"
rand = "0.8"
sha2 = "0.10"
hex = "0.4"
rhai = "1.17"
tokio = { version = "1", features = ["full"] }
futures-util = "0.3"
tungstenite = "0.21"
tokio-tungstenite = "0.21"
egui = "0.28"
eframe = { version = "0.28", default-features = true, features = ["wgpu"] }
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] } # for optional Ollama client
