[workspace]
members = [
  "astraweave-core",
  "astraweave-ai",
  "astraweave-sdk",
  "examples/hello_companion",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
anyhow = "1"
thiserror = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rand = "0.8"
