[package]
name = "rhai_authoring"
version = "0.1.0"
license.workspace = true
edition = "2021"

[dependencies]
anyhow = { workspace = true }
serde_json = { workspace = true }
astraweave-author = { path = "../../astraweave-author" }
