[package]
name = "weaving_pcg_demo"
version = "0.1.0"
license.workspace = true
edition = "2021"

[dependencies]
anyhow = { workspace = true }
astraweave-core = { path = "../../astraweave-core" }
rand = { workspace = true }
