[package]
name = "asset_signing"
version = "0.1.0"
edition = "2021"
license = { workspace = true }

[dependencies]
ed25519-dalek = { workspace = true, features = ["rand_core"] }
sha2 = { workspace = true }
rand = "0.8"
