blank_issues_enabled: false
contact_links:
  - name: Security Vulnerability
    url: https://github.com/lazyxeon/Veilweaver-Threads-of-Eternity/blob/main/SECURITY.md
    about: Please report security vulnerabilities according to our security policy.
  - name: Community Discussions
    url: https://github.com/lazyxeon/Veilweaver-Threads-of-Eternity/discussions
    about: Please ask and answer questions here.