[package]
name = "aw_release"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "aw_release"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap = { version = "4", features = ["derive"] }
semver.workspace = true
toml.workspace = true
serde.workspace = true
serde_json.workspace = true