[package]
name = "astraweave-render"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
bytemuck = { workspace = true }
glam = { workspace = true }
wgpu = { workspace = true }
winit = { workspace = true }
pollster = { workspace = true }
