[package]
name = "astraweave-audio"
version = "0.1.0"
license.workspace = true
edition = "2021"

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }
rand = { workspace = true }
glam = { workspace = true }
rodio = { workspace = true }
astraweave-gameplay = { path = "../astraweave-gameplay" }

[features]
mock_tts = ["dep:hound"]

[dependencies.hound]
version = "3"
optional = true

[dev-dependencies]
hound = "3"
criterion = "0.5"

[[bench]]
name = "audio_benchmarks"
harness = false
