[package]
name = "phase6_integration_demo"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
rand = { workspace = true }
astraweave-ecs = { workspace = true }
astraweave-core = { workspace = true }
astraweave-ai = { workspace = true }
astraweave-net-ecs = { workspace = true }
astraweave-persistence-ecs = { workspace = true }
astraweave-stress-test = { workspace = true }
astraweave-security = { workspace = true }
astraweave-physics = { workspace = true }
astraweave-nav = { workspace = true }