[package]
name = "terrain_demo"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
glam.workspace = true
astraweave-terrain = { path = "../../astraweave-terrain" }
astraweave-render = { path = "../../astraweave-render" }
clap = { version = "4.5", features = ["derive"] }