# Desert Environment Texture Pack  
name = "Desert"
description = "A harsh desert environment with sandy dunes and sparse vegetation"

[ground]
texture = "sand.png"  # Now using proper sand texture
scale = 8.0
color_tint = [1.0, 1.0, 1.0, 1.0]  # Neutral tint to preserve texture colors

[structures]
# Desert settlements using stone
[[structures.buildings]]
type = "adobe_house"
base_texture = "stone.ktx2"
roof_texture = "stone.ktx2"
probability = 0.05
size_range = [1.5, 3.0]

[sky]
horizon_color = [0.9, 0.7, 0.6]
zenith_color = [0.4, 0.6, 0.8]
sun_color = [1.0, 0.8, 0.6]

[ambient]
light_color = [1.0, 0.9, 0.7]
light_intensity = 0.8
fog_color = [0.9, 0.8, 0.7]
fog_density = 0.01

[materials.tree_bark]
albedo = "materials/tree_bark.png"
normal = "materials/tree_bark_n.png"
mra = "materials/tree_bark_mra.png"

[materials.tree_leaves]
albedo = "materials/tree_leaves.png"
normal = "materials/tree_leaves_n.png"
mra = "materials/tree_leaves_mra.png"

[materials.rock_lichen]
albedo = "materials/rock_lichen.png"
normal = "materials/rock_lichen_n.png"
mra = "materials/rock_lichen_mra.png"

[materials.rock_slate]
albedo = "materials/rock_slate.png"
normal = "materials/rock_slate_n.png"
mra = "materials/rock_slate_mra.png"

[materials.plaster]
albedo = "materials/plaster.png"
normal = "materials/plaster_n.png"
mra = "materials/plaster_mra.png"

[materials.roof_tile]
albedo = "materials/roof_tile.png"
normal = "materials/roof_tile_n.png"
mra = "materials/roof_tile_mra.png"

[materials.cloth]
albedo = "materials/cloth.png"
normal = "materials/cloth_n.png"
mra = "materials/cloth_mra.png"