# Grassland Environment Texture Pack
name = "Grassland"
description = "A peaceful grassland environment with rolling hills and scattered trees"

[ground]
texture = "grass.ktx2"
scale = 4.0
color_tint = [0.8, 1.0, 0.6, 1.0]

[structures]
# Simple houses using stone base and wood roof
[[structures.buildings]]
type = "cottage"
base_texture = "stone.ktx2"
roof_texture = "dirt.ktx2"  # Using dirt as thatch for now
probability = 0.1
size_range = [2.0, 4.0]

[sky]
# Sky gradient colors  
horizon_color = [0.7, 0.8, 0.9]
zenith_color = [0.3, 0.5, 0.8]
sun_color = [1.0, 0.9, 0.7]

[ambient]
light_color = [1.0, 0.95, 0.8]
light_intensity = 0.6
fog_color = [0.8, 0.85, 0.9]
fog_density = 0.02