[package]
name = "ollama_probe_example"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { workspace = true }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time"] }
futures-util = "0.3"
serde_json = "1.0"
anyhow = "1"
