[build]
# Optimize for CI environment - remove debuginfo in CI for faster builds
rustflags = ["-C", "debuginfo=0"]

[target.'cfg(all())']
# Enable sccache for faster compilation when available
# rustc-wrapper = "sccache"  # Enabled via environment variable in CI

[term]
color = "always"

[env]
# Configure sccache for optimal performance
SCCACHE_CACHE_SIZE = { value = "10G", relative = false }
SCCACHE_DIR = { value = "./target/sccache", relative = true }
SCCACHE_IDLE_TIMEOUT = { value = "0", relative = false }

[net]
# Optimize network settings for large workspace
git-fetch-with-cli = true
retry = 3

[profile.dev]
# Optimize development builds for workspace
opt-level = 0
debug = true
split-debuginfo = "unpacked"
debug-assertions = true
overflow-checks = true
lto = false
panic = "unwind"
incremental = true
codegen-units = 256

[profile.release]
# Optimize release builds for game engine performance
opt-level = 3
debug = false
split-debuginfo = "packed"
debug-assertions = false
overflow-checks = false
lto = "thin"
panic = "abort"
codegen-units = 1
strip = "symbols"

[profile.bench]
# Optimize benchmarks
inherits = "release"
debug = true

[profile.test]
# Optimize test builds for faster CI
inherits = "dev"
opt-level = 1
debug-assertions = true

[profile.dev.package."*"]
# Optimize dependencies in dev builds for faster compilation
opt-level = 1
debug = false
