[build]
# jobs = 4                      # Uncomment to limit parallelism locally
# rustc-wrapper = "sccache"     # Enabled via init_sccache function when available

[term]
color = "always"
progress.when = "auto"

[env]
# sccache tuning (safe defaults; adjust per CI runner)
SCCACHE_CACHE_SIZE = { value = "10G" }
SCCACHE_DIR = { value = "./target/sccache", relative = true }
SCCACHE_IDLE_TIMEOUT = { value = "0" }
SCCACHE_CACHE_MULTIARCH = { value = "1" }
SCCACHE_ERROR_LOG = { value = "./target/sccache-error.log", relative = true }

[net]
git-fetch-with-cli = true
retry = 3
offline = false

# Target-specific flags
[target.'cfg(not(target_env = "msvc"))']
# Favor host CPU on non-MSVC toolchains (keeps MSVC safer/portable)
rustflags = ["-C", "target-cpu=native"]

[alias]
check-all = "check --workspace --exclude astraweave-author --exclude visual_3d --exclude ui_controls_demo --exclude npc_town_demo --exclude rhai_authoring --exclude cutscene_render_demo --exclude weaving_playground --exclude combat_physics_demo --exclude navmesh_demo --exclude physics_demo3d --exclude debug_toolkit_demo --exclude aw_editor"
test-all  = "test  --workspace --lib --exclude astraweave-author --exclude visual_3d --exclude ui_controls_demo --exclude npc_town_demo --exclude rhai_authoring --exclude cutscene_render_demo --exclude weaving_playground --exclude combat_physics_demo --exclude navmesh_demo --exclude physics_demo3d --exclude debug_toolkit_demo --exclude aw_editor"
build-core = "build -p astraweave-core -p astraweave-ai -p astraweave-physics -p astraweave-nav -p astraweave-render -p hello_companion"
build-working = "build --workspace --exclude astraweave-author --exclude visual_3d --exclude ui_controls_demo --exclude npc_town_demo --exclude rhai_authoring --exclude cutscene_render_demo --exclude weaving_playground --exclude combat_physics_demo --exclude navmesh_demo --exclude physics_demo3d --exclude debug_toolkit_demo --exclude aw_editor"
clippy-all = "clippy --workspace --exclude astraweave-author --exclude visual_3d --exclude ui_controls_demo --exclude npc_town_demo --exclude rhai_authoring --exclude cutscene_render_demo --exclude weaving_playground --exclude combat_physics_demo --exclude navmesh_demo --exclude physics_demo3d --exclude debug_toolkit_demo --exclude aw_editor --all-features --all-targets"
deps-update = "update --workspace"
cache-clean = "clean --doc --release"
bench-core  = "bench -p astraweave-core -p astraweave-physics -p astraweave-nav"

[profile.dev]
opt-level = 0
debug = true
split-debuginfo = "unpacked"
debug-assertions = true
overflow-checks = true
lto = false
panic = "unwind"
incremental = true
codegen-units = 256
rpath = false

[profile.release]
opt-level = 3
debug = false
split-debuginfo = "packed"
debug-assertions = false
overflow-checks = false
lto = "thin"
panic = "abort"
codegen-units = 1
strip = "symbols"
rpath = false

[profile.bench]
inherits = "release"
debug = true
debug-assertions = false

[profile.test]
inherits = "dev"
opt-level = 1
debug-assertions = true
overflow-checks = true

# Speed up deps in all profiles
[profile.dev.package."*"]
opt-level = 1
debug = false
debug-assertions = false

[profile.test.package."*"]
opt-level = 1
debug = false

[profile.release.package."*"]
opt-level = 3
debug = false
