[package]
name = "ui_menu_demo"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
astraweave-ui = { path = "../../astraweave-ui" }
astraweave-audio = { path = "../../astraweave-audio", optional = true }  # Week 5 Day 2: Optional audio
wgpu = { workspace = true }
winit = { workspace = true }
env_logger = "0.11"
log = "0.4"
anyhow = { workspace = true }
pollster = "0.4"
glam = { workspace = true, optional = true }  # Week 5 Day 2: For vec3 (audio feature only)

[features]
default = []
audio = ["astraweave-audio", "glam"]  # Week 5 Day 2: Enable with --features audio
