[package]
name = "cinematics_timeline_demo"
version = "0.1.0"
license.workspace = true
edition = "2021"

[dependencies]
anyhow = { workspace = true }
astraweave-cinematics = { path = "../../astraweave-cinematics" }
