[biome]
name = "baked_test"

[[layer]]
key = "grass"
albedo = "../baked/grass.ktx2"
normal = "../baked/grass_n.ktx2"
mra    = "../baked/grass_mra.ktx2"
tiling = [2.0, 2.0]
triplanar_scale = 24.0

[[layer]]
key = "stone"
albedo = "../baked/stone.ktx2"
normal = "../baked/stone_n.ktx2"
mra    = "../baked/stone_mra.ktx2"
tiling = [1.5, 1.5]
triplanar_scale = 18.0

[[layer]]
key = "dirt"
albedo = "../baked/dirt.ktx2"
normal = "../baked/dirt_n.ktx2"
mra    = "../baked/dirt_mra.ktx2"
tiling = [2.0, 2.0]
triplanar_scale = 20.0

[[layer]]
key = "sand"
albedo = "../baked/sand.ktx2"
normal = "../baked/sand_n.ktx2"
mra    = "../baked/sand_mra.ktx2"
tiling = [1.8, 1.8]
triplanar_scale = 22.0

[[layer]]
key = "forest_floor"
albedo = "../baked/forest_floor.ktx2"
normal = "../baked/forest_floor_n.ktx2"
mra    = "../baked/forest_floor_mra.ktx2"
tiling = [2.2, 2.2]
triplanar_scale = 26.0

[[layer]]
key = "tree_bark"
albedo = "../baked/tree_bark.ktx2"
normal = "../baked/tree_bark_n.ktx2"
mra    = "../baked/tree_bark_mra.ktx2"
tiling = [1.0, 1.0]
triplanar_scale = 16.0
