[package]
name = "aw_asset_cli"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }
clap = { version = "4", features = ["derive"] }
uuid = { version = "1", features = ["v4"] }
walkdir = "2"
sha2 = { workspace = true }
hex = { workspace = true }
which = "8"
glob = "0.3"
gltf = "1"
image = "0.25"
astraweave-asset = { path = "../../astraweave-asset" }
tokio = { version = "1", features = ["full"] }
notify = "8"
flate2 = "1"  # for compression
ring = "0.17"  # for signing
base64 = "0.22"
ktx2 = "0.4"  # for KTX2 texture container format

# Optional: libktx-rs for production-grade BC compression
# Requires native libKTX library (see README for setup)
# libktx-rs = { version = "0.3", optional = true }

[features]
default = []
# Enable when libKTX native library is available
# professional-compression = ["libktx-rs"]