[package]
name = "world_partition_demo"
version = "0.1.0"
edition = "2021"

[dependencies]
astraweave-scene = { path = "../../astraweave-scene", features = ["ecs", "world-partition"] }
astraweave-ecs = { path = "../../astraweave-ecs" }
glam = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
rand = { workspace = true }