[package]
name = "parse_probe"
version = "0.1.0"
edition = "2021"

[dependencies]
astraweave-llm = { path = "..\\..\\astraweave-llm" }
astraweave-core = { path = "..\\..\\astraweave-core" }
anyhow = "1.0"

[workspace]

