[package]
name = "companion_profile"
version = "0.1.0"
license.workspace = true
edition = "2021"

[dependencies]
anyhow = { workspace = true }
astraweave-memory = { path = "../../astraweave-memory" }
