[biome]
name = "desert"

[[layer]]
key = "sand"
albedo = "../../sand.png"
normal = "../../sand_n.png"
mra    = "../../sand_mra.png"
tiling = [2.0, 2.0]
triplanar_scale = 24.0

[[layer]]
key = "rock_smooth"
albedo = "../../rock_slate.png"
normal = "../../rock_slate_n.png"
mra    = "../../rock_slate_mra.png"
tiling = [1.0, 1.0]
triplanar_scale = 18.0

[[layer]]
key = "stone"
albedo = "../../stone.png"
normal = "../../stone_n.png"
mra    = "../../stone_mra.png"
tiling = [1.5, 1.5]
triplanar_scale = 20.0

[[layer]]
key = "plaster"
albedo = "../../plaster.png"
normal = "../../plaster_n.png"
mra    = "../../plaster_mra.png"
tiling = [1.0, 1.0]
triplanar_scale = 12.0

[[layer]]
key = "cloth"
albedo = "../../cloth.png"
normal = "../../cloth_n.png"
mra    = "../../cloth_mra.png"
tiling = [1.0, 1.0]
triplanar_scale = 12.0
