[package]
name = "ecs_ai_demo"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
astraweave-core.workspace = true
astraweave-ecs.workspace = true
astraweave-ai.workspace = true
anyhow.workspace = true
