[package]
name = "aw_save_cli"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
time = { version = "0.3", features = ["formatting", "parsing", "macros", "serde-human-readable"] }
serde = { version = "1", features = ["derive"] }
postcard = { version = "1", features = ["alloc"] }
lz4_flex = "0.11"
uuid = { version = "1", features = ["v4", "serde"] }
aw-save = { path = "../../persistence/aw-save" }