[package]
name = "dialogue_voice_demo"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }
astraweave-audio = { path = "../../astraweave-audio" }
astraweave-gameplay = { path = "../../astraweave-gameplay" }
