[biome]
name = "forest"

[[layer]]
key = "forest_floor"
albedo = "../forest_floor.png"
normal = "../forest_floor_n.png"
mra    = "../forest_floor_mra.png"
tiling = [2.0, 2.0]
triplanar_scale = 20.0

[[layer]]
key = "tree_bark"
albedo = "../derived_1k/tree_bark.png"
normal = "../derived_1k/tree_bark_n.png"
mra    = "../derived_1k/tree_bark_mra.png"
tiling = [1.0, 1.0]
triplanar_scale = 10.0

[[layer]]
key = "tree_leaves"
albedo = "../derived_1k/tree_leaves.png"
normal = "../derived_1k/tree_leaves_n.png"
mra    = "../derived_1k/tree_leaves_mra.png"
tiling = [1.0, 1.0]
triplanar_scale = 8.0

[[layer]]
key = "rock_lichen"
albedo = "../derived_1k/rock_lichen.png"
normal = "../derived_1k/rock_lichen_n.png"
mra    = "../derived_1k/rock_lichen_mra.png"
tiling = [2.0, 2.0]
triplanar_scale = 18.0

[[layer]]
key = "rock_smooth"
albedo = "../rock_slate.png"
normal = "../rock_slate_n.png"
mra    = "../rock_slate_mra.png"
tiling = [1.0, 1.0]
triplanar_scale = 18.0
