[package]
name = "crafting_combat_demo"
version = "0.1.0"
license.workspace = true
edition = "2021"

[dependencies]
anyhow = { workspace = true }
glam = { workspace = true }
astraweave-gameplay = { path = "../../astraweave-gameplay" }
