name: Code Quality

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      
      - name: Install system dependencies (Linux)
        run: |
          sudo apt-get update
          # Core dev tools
          sudo apt-get install -y build-essential pkg-config cmake ninja-build
          # X11 + GL/EGL for winit/glutin/egui (wgpu paths)
          sudo apt-get install -y \
            libx11-dev libxi-dev libxcursor-dev libxrandr-dev libxinerama-dev \
            libxkbcommon-dev libxkbcommon-x11-dev libx11-xcb-dev \
            libxcb1-dev libxcb-randr0-dev libxcb-xfixes0-dev libxcb-shape0-dev libxcb-xkb-dev \
            libgl1-mesa-dev libegl1-mesa-dev
          # Wayland headers (winit can target both X11 and Wayland)
          sudo apt-get install -y wayland-protocols libwayland-dev
          # Audio for cpal/rodio
          sudo apt-get install -y libasound2-dev libpulse-dev libudev-dev
          # Vulkan runtime (not strictly needed to compile, helpful for runtime CI/tools)
          sudo apt-get install -y mesa-vulkan-drivers vulkan-tools
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
          
      - name: Clippy check - Core Components
        run: |
          cargo clippy \
            -p astraweave-core \
            -p astraweave-ai \
            -p astraweave-physics \
            -p astraweave-nav \
            -p astraweave-render \
            -p hello_companion \
            --all-features -- -D warnings

  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Format check - Core Components
        run: |
          cargo fmt --check \
            -p astraweave-core \
            -p astraweave-ai \
            -p astraweave-physics \
            -p astraweave-nav \
            -p astraweave-render \
            -p hello_companion