name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    
    - name: Install ALSA development libraries
      run: sudo apt-get update && sudo apt-get install -y libasound2-dev libudev-dev
    
    - name: Build - Core Components
      run: |
        cargo build --verbose \
          -p astraweave-core \
          -p astraweave-ai \
          -p astraweave-physics \
          -p astraweave-nav \
          -p astraweave-render \
          -p hello_companion
    - name: Run tests - Core Components
      run: |
        cargo test --verbose \
          -p astraweave-input \
          -p astraweave-core
