[package]
name = "astraweave-assets"
version = "0.1.0"
edition = "2021"
authors = ["AstraWeave Contributors"]
description = "Autonomous asset fetcher for PolyHaven CC0 materials, HDRIs, and models"
license = "MIT"

[[bin]]
name = "astraweave-assets"
path = "src/main.rs"

[dependencies]
# CLI and config
clap = { version = "4.5", features = ["derive", "cargo"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"

# Async runtime
tokio = { version = "1.40", features = ["full"] }
async-trait = "0.1"

# HTTP client
reqwest = { version = "0.12", features = ["json", "stream"] }

# Hashing and integrity
sha2 = "0.10"
hex = "0.4"

# Progress and UI
indicatif = "0.17"

# Error handling
anyhow = "1.0"
thiserror = "2.0"

# JSON output
serde_json = "1.0"

# Table formatting
prettytable-rs = "0.10"

# Timestamps
chrono = { version = "0.4", features = ["serde"] }

# Async stream utilities
futures-util = "0.3"

# Optional: KTX2 conversion (behind feature flag)
# basis-universal = { version = "0.3", optional = true }

[dev-dependencies]
tempfile = "3.13"
mockito = "1.6"
proptest = "1.8.0"
wiremock = "0.6.5"
assert_fs = "1.1.3"
predicates = "3.1.3"

[features]
default = []
ktx2 = []  # Future: KTX2 compression via basis-universal
live-api-tests = []  # Enable tests that call real PolyHaven API

[lib]
name = "astraweave_assets"
path = "src/lib.rs"

# Coverage configuration for cargo-tarpaulin
[package.metadata.tarpaulin]
# Exclude CLI code (tested manually) and test files
exclude-files = [
    "src/main.rs",
    "tests/*",
]
# Target 80%+ coverage
target = 80
